version: "2.1"

services:

  # контейнер с сервером
  server:
    build: .
    ports:
      - "9080:8000"
    command: ./server
    restart: always

    # контейнер с базой
  mysqldb:
    image: mysql:5.7.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=linkdb
    ports:
      - 3306:3306



